apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-pipeline-deploy-
spec:
  pipelineRef:
    name: petclinic-deploy
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: app-source-pvc
